import { test, expect } from '@playwright/test';
import { readCode, verifyEmail } from './mailbox';

test('email OTP registration and password recovery with session revocation', async ({ page }) => {
  const suffix = Date.now().toString();
  const email = `otp-${suffix}@example.com`;
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/register');
  await page.getByLabel('Full Name', { exact: true }).fill('OTP Browser Patient');
  await page.getByLabel('Email Address', { exact: true }).fill(email);
  await page.getByLabel('Phone Number', { exact: true }).fill('016' + suffix.slice(-8));
  await page.getByLabel('Password', { exact: true }).fill('OriginalPassword123!');
  await verifyEmail(page, email);
  const signup = await readCode(email);
  await page.getByLabel('Email verification code', { exact: true }).fill(signup === '999999' ? '888888' : '999999');
  await page.getByRole('button', { name: 'Register as Patient', exact: true }).click();
  await expect(page.getByText('The verification code is invalid or expired. Request a new code.')).toBeVisible();
  await page.getByLabel('Email verification code', { exact: true }).fill(signup);
  await page.getByRole('button', { name: 'Register as Patient', exact: true }).click();
  await expect(page).toHaveURL(/dashboard\/patient/);
  const oldToken = await page.evaluate(() => localStorage.getItem('spandan_access_token'));
  await page.goto('/forgot-password');
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByRole('button', { name: 'Send reset code', exact: true }).click();
  await expect(page.getByLabel('New password', { exact: true })).toBeVisible();
  const reset = await readCode(email);
  await page.getByLabel('Email verification code', { exact: true }).fill(reset === '999999' ? '888888' : '999999');
  await page.getByLabel('New password', { exact: true }).fill('ReplacementPassword123!');
  await page.getByLabel('Confirm new password', { exact: true }).fill('ReplacementPassword123!');
  await page.getByRole('button', { name: 'Reset password', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('The verification code is invalid or expired. Request a new code.');
  await page.getByLabel('Email verification code', { exact: true }).fill(reset);
  await page.getByRole('button', { name: 'Reset password', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Password reset successfully. Sign in with your new password.');
  const revoked = await page.request.get('/api/v1/auth/me', { headers: { Authorization: `Bearer ${oldToken}` } });
  expect(revoked.status()).toBe(401);
  expect(await page.evaluate(() => localStorage.getItem('spandan_access_token'))).toBeNull();
  await page.getByRole('link', { name: 'Back to sign in', exact: true }).click();
  await page.getByLabel('Email Address', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill('ReplacementPassword123!');
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await expect(page).toHaveURL(/dashboard\/patient/);
});
